# Lab 4.1 Feature Extraction

Name: Anas Kabir

Course: Machine Learning

Performed in: Jupyter Notebook (Anaconda)

In [1]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd

data = {
    'Datetime': [
        '2024-01-01 01:00:00',
        '2024-01-01 02:00:00',
        '2024-03-15 03:00:00',
        '2024-07-20 04:00:00',
        '2024-10-10 05:00:00'
    ],
    'AEP_MW': [
        12379,
        11935,
        11692,
        11597,
        11681
    ],
    'Date': [
        '2024-01-01',
        '2024-01-01',
        '2024-03-15',
        '2024-07-20',
        '2024-10-10'
    ],
    'Holiday': [
        0,0,0,0,0
    ]
}

df = pd.DataFrame(data)

df.to_csv('4_AEP_Introducing_holidays.csv',
          index=False)

print("CSV file created successfully")

CSV file created successfully

In [4]:
df = pd.read_csv('4_AEP_Introducing_holidays.csv',
                 parse_dates=['Datetime'])

df.head()

             Datetime  AEP_MW        Date  Holiday
0 2024-01-01 01:00:00   12379  2024-01-01        0
1 2024-01-01 02:00:00   11935  2024-01-01        0
2 2024-03-15 03:00:00   11692  2024-03-15        0
3 2024-07-20 04:00:00   11597  2024-07-20        0
4 2024-10-10 05:00:00   11681  2024-10-10        0

In [5]:
df['Hour'] = df['Datetime'].dt.hour

df['Month'] = df['Datetime'].dt.month

df['Day_Of_Week'] = df['Datetime'].dt.weekday

df['Week'] = df['Datetime'].dt.isocalendar().week

df['yearday'] = df['Datetime'].dt.dayofyear

df['quarter'] = df['Datetime'].dt.quarter

df['weekend'] = (df['Day_Of_Week'] >= 5).astype("int")

df['day_night'] = ((df['Hour'] >= 8) & (df['Hour'] <= 16)).astype("int")

df.head()

,Datetime,AEP_MW,Date,Holiday,Hour,Month,Day_Of_Week,Week,yearday,quarter,weekend,day_night
0,2024-01-01 01:00:00,12379,2024-01-01,0,1,1,0,1,1,1,0,0
1,2024-01-01 02:00:00,11935,2024-01-01,0,2,1,0,1,1,1,0,0
2,2024-03-15 03:00:00,11692,2024-03-15,0,3,3,4,11,75,1,0,0
3,2024-07-20 04:00:00,11597,2024-07-20,0,4,7,5,29,202,3,1,0
4,2024-10-10 05:00:00,11681,2024-10-10,0,5,10,3,41,284,4,0,0

In [6]:
df['winter'] = ((df['Month'] == 12) | 
                (df['Month'] == 1) | 
                (df['Month'] == 2)).astype("int")

df['spring'] = ((df['Month'] == 3) | 
                (df['Month'] == 4) | 
                (df['Month'] == 5)).astype("int")

df['summer'] = ((df['Month'] == 6) | 
                (df['Month'] == 7) | 
                (df['Month'] == 8)).astype("int")

df['fall'] = ((df['Month'] == 9) | 
              (df['Month'] == 10) | 
              (df['Month'] == 11)).astype("int")

df.tail()

,Datetime,AEP_MW,Date,Holiday,Hour,Month,Day_Of_Week,Week,yearday,quarter,weekend,day_night,winter,spring,summer,fall
0,2024-01-01 01:00:00,12379,2024-01-01,0,1,1,0,1,1,1,0,0,1,0,0,0
1,2024-01-01 02:00:00,11935,2024-01-01,0,2,1,0,1,1,1,0,0,1,0,0,0
2,2024-03-15 03:00:00,11692,2024-03-15,0,3,3,4,11,75,1,0,0,0,1,0,0
3,2024-07-20 04:00:00,11597,2024-07-20,0,4,7,5,29,202,3,1,0,0,0,1,0
4,2024-10-10 05:00:00,11681,2024-10-10,0,5,10,3,41,284,4,0,0,0,0,0,1

In [7]:
df.rename(columns={
    'AEP_MW': 'aep',
    'yearday': 'year_day',
    'Week': 'week_no',
    'Holiday': 'holiday',
    'Hour': 'hour',
    'Month': 'month',
    'Day_Of_Week': 'day_of_week'
}, inplace=True)

df.head()

,Datetime,aep,Date,holiday,hour,month,day_of_week,week_no,year_day,quarter,weekend,day_night,winter,spring,summer,fall
0,2024-01-01 01:00:00,12379,2024-01-01,0,1,1,0,1,1,1,0,0,1,0,0,0
1,2024-01-01 02:00:00,11935,2024-01-01,0,2,1,0,1,1,1,0,0,1,0,0,0
2,2024-03-15 03:00:00,11692,2024-03-15,0,3,3,4,11,75,1,0,0,0,1,0,0
3,2024-07-20 04:00:00,11597,2024-07-20,0,4,7,5,29,202,3,1,0,0,0,1,0
4,2024-10-10 05:00:00,11681,2024-10-10,0,5,10,3,41,284,4,0,0,0,0,0,1

In [8]:
df = df.reindex(columns=[
    'Datetime', 'aep', 'year_day', 'holiday', 'weekend',
    'winter', 'spring', 'summer', 'fall',
    'hour', 'month', 'day_of_week'
])

df.head()

,Datetime,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
0,2024-01-01 01:00:00,12379,1,0,0,1,0,0,0,1,1,0
1,2024-01-01 02:00:00,11935,1,0,0,1,0,0,0,2,1,0
2,2024-03-15 03:00:00,11692,75,0,0,0,1,0,0,3,3,4
3,2024-07-20 04:00:00,11597,202,0,1,0,0,1,0,4,7,5
4,2024-10-10 05:00:00,11681,284,0,0,0,0,0,1,5,10,3

In [9]:
df.to_csv('5_features_extracted.csv', index=False)

print("Feature extracted CSV saved successfully")

Feature extracted CSV saved successfully