# Lab 5 AEP Normalization One Hot and Cyclic Encoding

Name: Anas Kabir

Course: Machine Learning

Performed in: Jupyter Notebook (Anaconda)

Objective:
To apply normalization, one hot encoding, and cyclic feature transformation on AEP dataset for machine learning preprocessing.

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('5_features_extracted.csv')

df.head()

,Datetime,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
0,2024-01-01 01:00:00,12379,1,0,0,1,0,0,0,1,1,0
1,2024-01-01 02:00:00,11935,1,0,0,1,0,0,0,2,1,0
2,2024-03-15 03:00:00,11692,75,0,0,0,1,0,0,3,3,4
3,2024-07-20 04:00:00,11597,202,0,1,0,0,1,0,4,7,5
4,2024-10-10 05:00:00,11681,284,0,0,0,0,0,1,5,10,3

In [3]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['aep']] = scaler.fit_transform(df[['aep']])

df.head()

,Datetime,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
0,2024-01-01 01:00:00,1.000000,1,0,0,1,0,0,0,1,1,0
1,2024-01-01 02:00:00,0.432225,1,0,0,1,0,0,0,2,1,0
2,2024-03-15 03:00:00,0.121483,75,0,0,0,1,0,0,3,3,4
3,2024-07-20 04:00:00,0.000000,202,0,1,0,0,1,0,4,7,5
4,2024-10-10 05:00:00,0.107417,284,0,0,0,0,0,1,5,10,3

In [4]:
df = pd.get_dummies(
    df,
    columns=['month', 'day_of_week'],
    dtype=int
)

df.head()

,Datetime,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month_1,month_3,month_7,month_10,day_of_week_0,day_of_week_3,day_of_week_4,day_of_week_5
0,2024-01-01 01:00:00,1.000000,1,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0
1,2024-01-01 02:00:00,0.432225,1,0,0,1,0,0,0,2,1,0,0,0,1,0,0,0
2,2024-03-15 03:00:00,0.121483,75,0,0,0,1,0,0,3,0,1,0,0,0,0,1,0
3,2024-07-20 04:00:00,0.000000,202,0,1,0,0,1,0,4,0,0,1,0,0,0,0,1
4,2024-10-10 05:00:00,0.107417,284,0,0,0,0,0,1,5,0,0,0,1,0,1,0,0

In [5]:
df['hour_sin'] = np.sin(2 * np.pi * df['hour']/24)

df['hour_cos'] = np.cos(2 * np.pi * df['hour']/24)

df.head()

,Datetime,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month_1,month_3,month_7,month_10,day_of_week_0,day_of_week_3,day_of_week_4,day_of_week_5,hour_sin,hour_cos
0,2024-01-01 01:00:00,1.000000,1,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0.258819,0.965926
1,2024-01-01 02:00:00,0.432225,1,0,0,1,0,0,0,2,1,0,0,0,1,0,0,0,0.500000,0.866025
2,2024-03-15 03:00:00,0.121483,75,0,0,0,1,0,0,3,0,1,0,0,0,0,1,0,0.707107,0.707107
3,2024-07-20 04:00:00,0.000000,202,0,1,0,0,1,0,4,0,0,1,0,0,0,0,1,0.866025,0.500000
4,2024-10-10 05:00:00,0.107417,284,0,0,0,0,0,1,5,0,0,0,1,0,1,0,0,0.965926,0.258819

In [6]:
df.to_csv('6_AEP_normalized_encoded.csv', index=False)

print("Normalized and encoded CSV saved successfully")

Normalized and encoded CSV saved successfully