# Lab 2.2 Pandas

Name: Anas Kabir

Course: Machine Learning

Performed in: Jupyter Notebook (Anaconda)

Objective:
To learn basic Pandas operations including Series, DataFrame, reading data, selecting columns, and basic data analysis.

In [1]:
import pandas as pd

print("Pandas imported successfully")

Pandas imported successfully

In [2]:
marks = pd.Series([85, 90, 78, 92, 88])

print(marks)

0    85
1    90
2    78
3    92
4    88
dtype: int64

In [3]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Anas", "Zara"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)

df

    Name  Age  Marks
0    Ali   20     85
1  Ahmed   21     90
2   Sara   19     78
3   Anas   22     92
4   Zara   20     88

In [4]:
print("First five rows:")

print(df.head())


print("Data Information:")

df.info()

First five rows:
    Name  Age  Marks
0    Ali   20     85
1  Ahmed   21     90
2   Sara   19     78
3   Anas   22     92
4   Zara   20     88
Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [5]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   20.400000  86.600000
std     1.140175   5.458938
min    19.000000  78.000000
25%    20.000000  85.000000
50%    20.000000  88.000000
75%    21.000000  90.000000
max    22.000000  92.000000

In [6]:
names = df["Name"]

marks = df["Marks"]


print("Student Names:")

print(names)


print("Student Marks:")

print(marks)

Student Names:
0      Ali
1    Ahmed
2     Sara
3     Anas
4     Zara
Name: Name, dtype: object
Student Marks:
0    85
1    90
2    78
3    92
4    88
Name: Marks, dtype: int64

In [7]:
df["Grade"] = [
    "B",
    "A",
    "C",
    "A",
    "B"
]


df

    Name  Age  Marks Grade
0    Ali   20     85     B
1  Ahmed   21     90     A
2   Sara   19     78     C
3   Anas   22     92     A
4   Zara   20     88     B

In [8]:
high_marks = df[df["Marks"] >= 85]


print("Students with high marks:")


high_marks

Students with high marks:

    Name  Age  Marks Grade
0    Ali   20     85     B
1  Ahmed   21     90     A
3   Anas   22     92     A
4   Zara   20     88     B

In [9]:
sorted_data = df.sort_values(
    by="Marks",
    ascending=False
)


sorted_data

    Name  Age  Marks Grade
3   Anas   22     92     A
1  Ahmed   21     90     A
4   Zara   20     88     B
0    Ali   20     85     B
2   Sara   19     78     C

In [10]:
df.to_csv(
    "students_data.csv",
    index=False
)


print("CSV file saved successfully")

CSV file saved successfully

In [11]:
new_data = pd.read_csv(
    "students_data.csv"
)


new_data

    Name  Age  Marks Grade
0    Ali   20     85     B
1  Ahmed   21     90     A
2   Sara   19     78     C
3   Anas   22     92     A
4   Zara   20     88     B

In [12]:
print("Missing Values:")


print(new_data.isnull().sum())

Missing Values:
Name     0
Age      0
Marks    0
Grade    0
dtype: int64

## Conclusion

In this lab, Pandas library was used for data handling and analysis.

A Series and DataFrame were created successfully.

Different operations such as selecting columns, adding new columns, filtering, sorting, and checking missing values were performed.

The DataFrame was saved into a CSV file and loaded again using Pandas.

Pandas provides simple and powerful tools for data preprocessing in machine learning.